// Mock data for demo mode when Supabase is not configured
import type { Activity, Driver, Risk, Technology } from '@/types/database';

export const MOCK_TECHNOLOGIES: Technology[] = [
  {
    id: 'mock-preset-1',
    code: 'TECH_POWER_PLATFORM',
    name: 'Power Platform',
    description: 'Technology for Power Platform requirements.',
    tech_category: 'POWER_PLATFORM',
    color: '#742774',
    icon: 'zap',
    sort_order: 1,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-preset-2',
    code: 'TECH_BACKEND',
    name: 'Backend',
    description: 'Technology for REST API backend implementation.',
    tech_category: 'BACKEND',
    color: '#2563eb',
    icon: 'server',
    sort_order: 2,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-preset-3',
    code: 'TECH_FRONTEND',
    name: 'Frontend – React SPA',
    description: 'Technology for React Single Page Application development.',
    tech_category: 'FRONTEND',
    color: '#0ea5e9',
    icon: 'layout',
    sort_order: 3,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-preset-usu-1',
    code: 'TECH_USU',
    name: 'USU – Standard',
    description: 'Technology for USU Service Management projects.',
    tech_category: 'USU',
    color: '#16a34a',
    icon: 'cog',
    sort_order: 4,
    is_custom: false,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  // Power Platform
  {
    id: 'mock-act-1',
    code: 'PP_ANL_ALIGN',
    name: 'Allineamento analisi requisiti',
    description: 'Sessioni di allineamento funzionale/tecnico sul requisito in ambito Power Platform.',
    base_hours: 4.0,
    tech_category: 'POWER_PLATFORM',
    group: 'ANALYSIS',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-2',
    code: 'PP_DV_FIELD',
    name: 'Creazione campi Dataverse',
    description: 'Definizione e creazione di nuovi campi su tabelle Dataverse, incluse proprietà base e relazioni semplici.',
    base_hours: 2.0,
    tech_category: 'POWER_PLATFORM',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-3',
    code: 'PP_DV_FORM',
    name: 'Configurazione form Dataverse',
    description: 'Configurazione layout form, controlli e logica di base lato Dataverse.',
    base_hours: 4.0,
    tech_category: 'POWER_PLATFORM',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-4',
    code: 'PP_FLOW_SIMPLE',
    name: 'Power Automate Flow semplice',
    description: 'Implementazione di un flusso Power Automate con logica lineare e poche condizioni.',
    base_hours: 4.0,
    tech_category: 'POWER_PLATFORM',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-5',
    code: 'PP_FLOW_COMPLEX',
    name: 'Power Automate Flow complesso',
    description: 'Flusso con più condizioni, rami paralleli o integrazioni esterne.',
    base_hours: 8.0,
    tech_category: 'POWER_PLATFORM',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-6',
    code: 'PP_BUSINESS_RULE',
    name: 'Business Rule Dataverse',
    description: 'Configurazione di regole di business lato Dataverse (validazioni, calcoli, visibilità campi).',
    base_hours: 2.0,
    tech_category: 'POWER_PLATFORM',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-7',
    code: 'PP_E2E_TEST',
    name: 'Test end-to-end Power Platform',
    description: 'Test end-to-end della soluzione in ambiente di test/pre-produzione.',
    base_hours: 8.0,
    tech_category: 'POWER_PLATFORM',
    group: 'TEST',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-8',
    code: 'PP_UAT_RUN',
    name: 'Supporto UAT',
    description: 'Supporto agli utenti per esecuzione User Acceptance Test, raccolta feedback e piccoli aggiustamenti.',
    base_hours: 8.0,
    tech_category: 'POWER_PLATFORM',
    group: 'TEST',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-9',
    code: 'PP_DEPLOY',
    name: 'Deploy soluzione Power Platform',
    description: 'Preparazione e rilascio soluzione tra ambienti (dev/test/prod) con validazioni base.',
    base_hours: 4.0,
    tech_category: 'POWER_PLATFORM',
    group: 'OPS',
    active: true,
    created_at: new Date().toISOString(),
  },

  // Backend
  {
    id: 'mock-act-10',
    code: 'BE_ANL_ALIGN',
    name: 'Analisi API / backend',
    description: 'Analisi requisiti specifici per endpoint, logica di business e sicurezza.',
    base_hours: 4.0,
    tech_category: 'BACKEND',
    group: 'ANALYSIS',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-11',
    code: 'BE_API_SIMPLE',
    name: 'Endpoint API semplice',
    description: 'Implementazione di un endpoint REST con logica lineare e CRUD standard.',
    base_hours: 6.0,
    tech_category: 'BACKEND',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-12',
    code: 'BE_API_COMPLEX',
    name: 'Endpoint API complesso',
    description: 'Endpoint con logica di business articolata, orchestrazione di più servizi o chiamate esterne.',
    base_hours: 12.0,
    tech_category: 'BACKEND',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-13',
    code: 'BE_DB_MIGRATION',
    name: 'Migrazione schema DB',
    description: 'Creazione o modifica di schema DB (tabelle, indici, vincoli) e relativa migrazione.',
    base_hours: 8.0,
    tech_category: 'BACKEND',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-14',
    code: 'BE_UNIT_TEST',
    name: 'Unit test backend',
    description: 'Implementazione di unit test per servizi o controller backend.',
    base_hours: 4.0,
    tech_category: 'BACKEND',
    group: 'TEST',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-15',
    code: 'BE_INT_TEST',
    name: 'Integration test backend',
    description: 'Test di integrazione tra componenti backend e/o servizi esterni.',
    base_hours: 6.0,
    tech_category: 'BACKEND',
    group: 'TEST',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-16',
    code: 'BE_LOGGING',
    name: 'Logging & monitoring',
    description: 'Configurazione logging, metriche base e integrazione con sistema di monitoring.',
    base_hours: 4.0,
    tech_category: 'BACKEND',
    group: 'OPS',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-17',
    code: 'BE_DEPLOY',
    name: 'Deploy backend',
    description: 'Preparazione pipeline e rilascio in ambiente di destinazione.',
    base_hours: 4.0,
    tech_category: 'BACKEND',
    group: 'OPS',
    active: true,
    created_at: new Date().toISOString(),
  },

  // Frontend
  {
    id: 'mock-act-18',
    code: 'FE_ANL_UX',
    name: 'Analisi UX/UI',
    description: 'Analisi esigenze UX/UI per schermata o flusso frontend.',
    base_hours: 4.0,
    tech_category: 'FRONTEND',
    group: 'ANALYSIS',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-19',
    code: 'FE_UI_COMPONENT',
    name: 'Componente UI',
    description: 'Implementazione di un componente UI (React o equivalente) con logica base di presentazione.',
    base_hours: 4.0,
    tech_category: 'FRONTEND',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-20',
    code: 'FE_FORM',
    name: 'Form complesso',
    description: 'Implementazione form con validazioni, stato complesso e integrazione API.',
    base_hours: 8.0,
    tech_category: 'FRONTEND',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-21',
    code: 'FE_STATE_MGMT',
    name: 'Gestione stato',
    description: 'Configurazione e/o estensione di store globale (es. Redux, Zustand) o stato condiviso.',
    base_hours: 6.0,
    tech_category: 'FRONTEND',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-22',
    code: 'FE_API_INTEGRATION',
    name: 'Integrazione API',
    description: 'Integrazione con API esistenti, gestione errori e loading.',
    base_hours: 4.0,
    tech_category: 'FRONTEND',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-23',
    code: 'FE_UNIT_TEST',
    name: 'Unit test UI',
    description: 'Test unitari su componenti UI.',
    base_hours: 4.0,
    tech_category: 'FRONTEND',
    group: 'TEST',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-24',
    code: 'FE_E2E_TEST',
    name: 'E2E test frontend',
    description: 'Test end-to-end di flussi utente critici.',
    base_hours: 6.0,
    tech_category: 'FRONTEND',
    group: 'TEST',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-25',
    code: 'FE_DEPLOY',
    name: 'Deploy frontend',
    description: 'Build e pubblicazione applicazione frontend (CDN, hosting, configurazione base).',
    base_hours: 4.0,
    tech_category: 'FRONTEND',
    group: 'OPS',
    active: true,
    created_at: new Date().toISOString(),
  },

  // Multi-stack
  {
    id: 'mock-act-26',
    code: 'CRS_KICKOFF',
    name: 'Kickoff tecnico',
    description: 'Kickoff con team cross-funzionali per allineamento su scope, dipendenze e rischi.',
    base_hours: 4.0,
    tech_category: 'MULTI',
    group: 'GOVERNANCE',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-27',
    code: 'CRS_DOC',
    name: 'Documentazione tecnica',
    description: 'Redazione o aggiornamento documentazione tecnica fondamentale per il requisito.',
    base_hours: 4.0,
    tech_category: 'MULTI',
    group: 'GOVERNANCE',
    active: true,
    created_at: new Date().toISOString(),
  },
  // USU
  {
    id: 'mock-act-usu-1',
    code: 'USU_ACTION_PLUGIN',
    name: 'Action Plugin (Jython/Java)',
    description: 'Implementare un plugin/azione custom che esegua logiche complesse su chiamata (es. recupero/elaborazione dati da servizio esterno), scritto in Jython con wrapper Java quando necessario.',
    base_hours: 32.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-2',
    code: 'USU_XOBJ_SET',
    name: 'Creazione e collegamento XObjSet',
    description: 'Definire due XObjSet e implementare la relazione (referenza, join, sincronizzazione) con operazioni CRUD coerenti.',
    base_hours: 50.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-3',
    code: 'USU_DYN_FORM',
    name: 'Estensione Dynamic Form',
    description: 'Aggiungere campi dinamici visibili/obbligatori in funzione di valori selezionati, con validazioni lato client/server.',
    base_hours: 21.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-4',
    code: 'USU_JOB_SCHED',
    name: 'Job Scheduler (Background Job)',
    description: 'Implementare job pianificati per compiti ricorrenti (p.es. pulizia, invio report, update dati).',
    base_hours: 35.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-5',
    code: 'USU_API_INT',
    name: 'Integrazione API esterna',
    description: 'Collegare USU a un servizio esterno per arricchire ticket (es. lookup anagrafica, meteo, ERP).',
    base_hours: 75.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-6',
    code: 'USU_WORKFLOW',
    name: 'Custom Workflow',
    description: 'Definire nuovi stati e regole di transizione (es. “Verifica Tecnica”), con automazioni e notifiche.',
    base_hours: 60.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-7',
    code: 'USU_LIST_VIEW',
    name: 'Custom List View Renderer',
    description: 'Modificare layout/colonne/interazioni di una list view per migliorare usabilità e filtraggio.',
    base_hours: 32.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-8',
    code: 'USU_WIDGET',
    name: 'Widget Dashboard custom',
    description: 'Realizzare un widget KPI/grafico integrato nella dashboard (es. conteggi SLA, trend).',
    base_hours: 40.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-9',
    code: 'USU_PERF_OPT',
    name: 'Analisi e miglioramento performance',
    description: 'Profiling e ottimizzazione queries e modello dati per una vista lenta.',
    base_hours: 36.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-10',
    code: 'USU_PDF_TMPL',
    name: 'Template PDF custom',
    description: 'Realizzare un template PDF per stampa ticket/report con layout e logo cliente.',
    base_hours: 14.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-11',
    code: 'USU_KPI_TRACK',
    name: 'Tracciamento KPI automatico',
    description: 'Calcolo e popolamento automatico di KPI per ticket (SLA, tempo apertura-chiusura, tempo in stato).',
    base_hours: 29.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-12',
    code: 'USU_RULE_ENG',
    name: 'Configurazione Motore di Regole',
    description: 'Implementare un motore / set di regole per azioni automatiche basate su condizioni (es. assegnazioni, cambi stati, notifiche).',
    base_hours: 42.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-13',
    code: 'USU_JYTHON_REF',
    name: 'Migrazione script Jython legacy',
    description: 'Revisione e refactor di script Jython legacy per uniformare stile, performance e compatibilità.',
    base_hours: 64.0,
    tech_category: 'USU',
    group: 'DEV',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-14',
    code: 'USU_SANDBOX',
    name: 'Creazione ambiente sandbox',
    description: 'Allestire un ambiente di test con dati anonimi ma realistici per collaudo e demo.',
    base_hours: 42.0,
    tech_category: 'USU',
    group: 'OPS',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-act-usu-15',
    code: 'USU_DOCS',
    name: 'Documentazione tecnica strutturata',
    description: 'Redigere una documentazione chiara dei flussi, customizzazioni e punti di estensione usati nel progetto.',
    base_hours: 21.0,
    tech_category: 'USU',
    group: 'GOVERNANCE',
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'mock-driver-1',
    code: 'COMPLEXITY',
    name: 'Complexity',
    description: 'Livello di complessità funzionale/tecnica del requisito.',
    options: [
      { value: 'LOW', label: 'Low', multiplier: 0.8 },
      { value: 'MEDIUM', label: 'Medium', multiplier: 1.0 },
      { value: 'HIGH', label: 'High', multiplier: 1.3 },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-driver-2',
    code: 'ENVIRONMENTS',
    name: 'Number of environments',
    description: 'Numero di ambienti coinvolti (dev/test/preprod/prod...).',
    options: [
      { value: 'ONE', label: '1 environment', multiplier: 1.0 },
      { value: 'TWO', label: '2 environments', multiplier: 1.2 },
      { value: 'THREE_PLUS', label: '3+ environments', multiplier: 1.3 },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-driver-3',
    code: 'REUSE',
    name: 'Reuse level',
    description: 'Quanto riutilizzo di componenti esistenti è possibile.',
    options: [
      { value: 'HIGH', label: 'High reuse', multiplier: 0.8 },
      { value: 'MEDIUM', label: 'Medium reuse', multiplier: 1.0 },
      { value: 'LOW', label: 'Low reuse', multiplier: 1.2 },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-driver-4',
    code: 'STAKEHOLDERS',
    name: 'Stakeholders',
    description: 'Numero di team o stakeholder coinvolti.',
    options: [
      { value: 'ONE_TEAM', label: '1 team', multiplier: 1.0 },
      { value: 'TWO_THREE', label: '2–3 team', multiplier: 1.2 },
      { value: 'FOUR_PLUS', label: '4+ team', multiplier: 1.5 },
    ],
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-driver-5',
    code: 'REGULATION',
    name: 'Regulation / Compliance',
    description: 'Impatto di normative, compliance o audit esterni.',
    options: [
      { value: 'NONE', label: 'No regulation', multiplier: 1.0 },
      { value: 'MEDIUM', label: 'Medium', multiplier: 1.1 },
      { value: 'HEAVY', label: 'Heavy', multiplier: 1.25 },
    ],
    created_at: new Date().toISOString(),
  },
];

export const MOCK_RISKS: Risk[] = [
  {
    id: 'mock-risk-1',
    code: 'R_INTEG_EXT',
    name: 'Integrazione con sistemi esterni',
    description: 'Il requisito prevede integrazioni con servizi o sistemi esterni non pienamente sotto il nostro controllo.',
    weight: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-risk-2',
    code: 'R_PERF',
    name: 'Performance critical',
    description: 'Requisiti stringenti di prestazioni (latenza, throughput, carico elevato).',
    weight: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-risk-3',
    code: 'R_AUDIT',
    name: 'Audit / Tracciabilità',
    description: 'Necessità di tracciare in modo dettagliato le operazioni per scopi di audit o compliance.',
    weight: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-risk-4',
    code: 'R_MIGRATION',
    name: 'Migrazione dati legacy',
    description: 'Migrazione o trasformazione di dati esistenti da sistemi legacy.',
    weight: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-risk-5',
    code: 'R_LEGACY',
    name: 'Dipendenza da legacy',
    description: 'Dipendenza forte da sistemi legacy, librerie obsolete o codice non manutenuto.',
    weight: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-risk-6',
    code: 'R_SCOPE_CHANGE',
    name: 'Scope instabile',
    description: 'Scope del requisito percepito come instabile o soggetto a molti cambiamenti.',
    weight: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-risk-7',
    code: 'R_SECURITY',
    name: 'Requisiti di sicurezza',
    description: 'Presenza di requisiti di sicurezza avanzati (autenticazione forte, cifratura, audit).',
    weight: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-risk-8',
    code: 'R_DEPENDENCIES',
    name: 'Dipendenze critiche',
    description: 'Dipendenze da altri team, progetti o componenti che possono causare blocchi.',
    weight: 4,
    created_at: new Date().toISOString(),
  },
];

// Smart mock AI suggestions based on keywords in description
export function getMockAISuggestions(description: string, preset: Technology): string[] {
  const descLower = description.toLowerCase();
  const techCategory = preset.tech_category;

  // Start with empty suggestions (no more template defaults)
  const suggestions: string[] = [];

  // Add intelligent suggestions based on keywords
  if (techCategory === 'POWER_PLATFORM') {
    if (descLower.includes('form') || descLower.includes('schermata')) {
      if (!suggestions.includes('PP_DV_FORM')) suggestions.push('PP_DV_FORM');
    }
    if (descLower.includes('workflow') || descLower.includes('automazione') || descLower.includes('notifica')) {
      if (!suggestions.includes('PP_FLOW_COMPLEX')) suggestions.push('PP_FLOW_COMPLEX');
    }
    if (descLower.includes('campo') || descLower.includes('field') || descLower.includes('dataverse')) {
      if (!suggestions.includes('PP_DV_FIELD')) suggestions.push('PP_DV_FIELD');
    }
  }

  if (techCategory === 'BACKEND') {
    if (descLower.includes('endpoint') || descLower.includes('api')) {
      if (!suggestions.includes('BE_API_SIMPLE')) suggestions.push('BE_API_SIMPLE');
    }
    if (descLower.includes('database') || descLower.includes('tabella') || descLower.includes('schema')) {
      if (!suggestions.includes('BE_DB_MIGRATION')) suggestions.push('BE_DB_MIGRATION');
    }
    if (descLower.includes('complesso') || descLower.includes('orchestrazione')) {
      if (!suggestions.includes('BE_API_COMPLEX')) suggestions.push('BE_API_COMPLEX');
    }
  }

  if (techCategory === 'FRONTEND') {
    if (descLower.includes('form') || descLower.includes('input') || descLower.includes('validazione')) {
      if (!suggestions.includes('FE_FORM')) suggestions.push('FE_FORM');
    }
    if (descLower.includes('componente') || descLower.includes('ui') || descLower.includes('interfaccia')) {
      if (!suggestions.includes('FE_UI_COMPONENT')) suggestions.push('FE_UI_COMPONENT');
    }
    if (descLower.includes('stato') || descLower.includes('store') || descLower.includes('redux')) {
      if (!suggestions.includes('FE_STATE_MGMT')) suggestions.push('FE_STATE_MGMT');
    }
  }

  return suggestions;
}