/**
 * Domain types for Project Custom Activities.
 *
 * Project activities are domain-specific deliverables generated by the AI
 * pipeline (Pass 3) during "Create Project from Documentation". They are
 * calibrated on the standard activity catalog's scale but with names,
 * descriptions, and effort tailored to the project's documentation.
 *
 * Each activity carries an intervention_type (NEW/MODIFY/CONFIGURE/MIGRATE)
 * and an effort_modifier to differentiate creation vs modification work.
 */

// ============================================================================
// Enums
// ============================================================================

export type InterventionType = 'NEW' | 'MODIFY' | 'CONFIGURE' | 'MIGRATE';

export type ActivityGroup = 'ANALYSIS' | 'DEV' | 'TEST' | 'OPS' | 'GOVERNANCE';

export type BlueprintNodeType = 'component' | 'dataDomain' | 'integration';

// ============================================================================
// Domain Type (camelCase)
// ============================================================================

export interface ProjectActivity {
    id?: string;
    projectId: string;
    code: string;
    name: string;
    description?: string;
    group: ActivityGroup;
    baseHours: number;
    smMultiplier: number;
    lgMultiplier: number;
    interventionType: InterventionType;
    effortModifier: number;
    sourceActivityCode?: string | null;
    blueprintNodeName?: string | null;
    blueprintNodeType?: BlueprintNodeType | null;
    aiRationale?: string | null;
    confidence?: number | null;
    isEnabled: boolean;
    position: number;
    createdAt?: string;
    updatedAt?: string;
}

// ============================================================================
// DB Row Type (snake_case, for Supabase interaction)
// ============================================================================

export interface ProjectActivityRow {
    id: string;
    project_id: string;
    code: string;
    name: string;
    description: string | null;
    group: string;
    base_hours: number;
    sm_multiplier: number;
    lg_multiplier: number;
    intervention_type: string;
    effort_modifier: number;
    source_activity_code: string | null;
    blueprint_node_name: string | null;
    blueprint_node_type: string | null;
    ai_rationale: string | null;
    confidence: number | null;
    is_enabled: boolean;
    position: number;
    created_at: string;
    updated_at: string;
}

// ============================================================================
// Create Input (for repository layer)
// ============================================================================

export interface CreateProjectActivityInput {
    projectId: string;
    code: string;
    name: string;
    description?: string;
    group: ActivityGroup;
    baseHours: number;
    smMultiplier?: number;
    lgMultiplier?: number;
    interventionType: InterventionType;
    effortModifier?: number;
    sourceActivityCode?: string | null;
    blueprintNodeName?: string | null;
    blueprintNodeType?: BlueprintNodeType | null;
    aiRationale?: string | null;
    confidence?: number | null;
    isEnabled?: boolean;
    position?: number;
}

// ============================================================================
// AI-Generated Activity (raw output from Pass 3, before persistence)
// ============================================================================

export interface GeneratedProjectActivity {
    code: string;
    name: string;
    description: string;
    group: ActivityGroup;
    baseHours: number;
    interventionType: InterventionType;
    effortModifier: number;
    sourceActivityCode: string | null;
    blueprintNodeName: string | null;
    blueprintNodeType: BlueprintNodeType | null;
    aiRationale: string;
    confidence: number;
}
